ur3:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: &loop_hz 125

  # joint_eff_controller:
  #   type: effort_controllers/JointEffortController
  #   joints: &robot_joints
  #     - shoulder_pan_joint
  #     - shoulder_lift_joint
  #     - elbow_joint
  #     - wrist_1_joint
  #     - wrist_2_joint
  #     - wrist_3_joint
  #   gains: # Required because we're controlling an effort interface
  #   shoulder_pan_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
  #   shoulder_lift_joint: {p: 6000,  d: 40, i: 1, i_clamp: 1}
  #   elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
  #   wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
  #   wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
  #   wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 

  shoulder_pan_joint_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_pan_joint
    pid: {p: 2000,  d: 20, i: 1, i_clamp: 1}
  shoulder_lift_joint_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_lift_joint
    pid: {p: 6000,  d: 40, i: 1, i_clamp: 1}
  elbow_joint_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_joint
    pid: {p: 2000,  d: 20, i: 1, i_clamp: 1}
  wrist_1_joint_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_1_joint
    pid: {p: 500,  d: 1, i: 1, i_clamp: 1}
  wrist_2_joint_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_2_joint
    pid: {p: 500,  d: 1, i: 1, i_clamp: 1}
  wrist_3_joint_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_3_joint
    pid: {p: 10,  d: 0.1, i: 0, i_clamp: 1}

# joint_eff_controller:
#   type: effort_controllers/JointEffortController
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gains:
#     shoulder_pan_joint: 
#       p: 2000
#       d: 20
#       i: 1
#       i_clamp: 1
#     shoulder_lift_joint:
#       p: 6000
#       d: 40
#       i: 1
#       i_clamp: 1
#     elbow_joint:
#       p: 2000
#       d: 20
#       i: 1
#       i_clamp: 1
#     wrist_1_joint:
#       p: 500
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_2_joint:
#       p: 500
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_3_joint:
#       p: 10
#       d: 0.1
#       i: 0
#       i_clamp: 1


# joint_group_eff_controller:
#   type: effort_controllers/JointGroupEffortController
#   joints: *robot_joints
